[update]
tasks = ["interfaces", "normalize", "translate", "transform"]

[update.interfaces]
paths = ["App/Sources"]

[update.normalize]
paths = ["App/Resources"]
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[update.translate]
paths = ["App/Resources"]
secret = ""
sourceLocale = "en"

[update.transform]
codePaths = ["App/Sources"]
localizablePaths = ["App/Resources"]
transformer = "swiftgenStructured"
supportedLanguageEnumPath = "App/Resources"
typeName = "BartyCrouch"
translateMethodName = "translate"

[lint]
paths = ["App/Resources"]
duplicateKeys = true
emptyValues = true
