name: Main

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: Build & Run Tests
        run: xcodebuild test -scheme App -destination 'platform=iOS Simulator,name=iPad Air (4th generation),OS=latest'
