name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs of this workflow on same branch
        uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  swift-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Mint
        run: git clone https://github.com/yonaskolb/Mint.git && cd Mint && make

      - name: Install Swift-Format
        run: mint install apple/swift-format

      - name: Run Swift-Format
        run: "! swift-format lint --recursive App/Sources Tests/Sources UITests/Sources 2>&1 | grep -q warning"

  tests:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build & Run Tests
        run: xcodebuild test -scheme App -destination 'platform=iOS Simulator,name=iPad Air (4th generation),OS=latest'
